# Generated by Django 3.1.5 on 2021-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
