# Generated by Django 3.1.5 on 2021-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
