# Generated by Django 3.1.5 on 2021-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='question',
            new_name='car_id',
        ),
    ]
