# Generated by Django 3.1.5 on 2021-02-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210205_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='car_id',
            new_name='car',
        ),
    ]
