# Generated by Django 3.1.5 on 2021-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210205_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
