# Generated by Django 3.1.5 on 2021-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210208_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
