# Generated by Django 3.1.5 on 2021-02-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210209_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
